#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Image-ExifTool
version:      3.72
version_from: lib/Image/ExifTool.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
